name: bacakuy_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.10.0
  cloud_firestore: 3.1.0
  font_awesome_flutter: 9.2.0
  google_fonts: 2.1.0
  url_launcher: 6.0.15
  firebase_auth: 3.3.0
  google_sign_in: 5.2.1
  firebase_database: 8.2.0
  carousel_slider: ^4.0.0
  curved_navigation_bar: 1.0.1
  bottom_navy_bar: 6.0.0
  shared_preferences: ^2.0.11
  provider: ^6.0.1
  intl: 0.17.0
  flutter_local_notifications: 9.1.5
  rxdart: 0.27.3
  get_storage: 2.0.3
  android_alarm_manager: 2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/json_model/
    - assets/images/
    - assets/icons/
  uses-material-design: true

